import { config } from "dotenv";

config();

const PORT=process.env.PORT;
const FRONTEND_URL=process.env.FRONTEND_URL;
const MONGOOSE_URI=process.env.MONGOOSE_URI;
const CLOUDINARY_API_KEY=process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET=process.env.CLOUDINARY_API_SECRET;
const CLOUDINARY_CLOUD_NAME=process.env.CLOUDINARY_CLOUD_NAME;
const COOKIE_EXPIRE=process.env.COOKIE_EXPIRE;
const JWT_SECRET_KEY=process.env.JWT_SECRET_KEY;
const JWT_EXPIRE=process.env.JWT_EXPIRE;
const SMTP_MAIL=process.env.SMTP_MAIL;
const SMTP_PASSWORD=process.env.SMTP_PASSWORD;
const SMTP_SERVICE=process.env.SMTP_SERVICE;

export {PORT,FRONTEND_URL,MONGOOSE_URI,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET,CLOUDINARY_CLOUD_NAME,COOKIE_EXPIRE,JWT_EXPIRE,JWT_SECRET_KEY,SMTP_MAIL,SMTP_PASSWORD,SMTP_SERVICE};